import { Router, type IRouter } from "express";
import healthRouter from "./health";
import clientsRouter from "./clients";
import platformsRouter from "./platforms";
import partnerConfigRouter from "./partner-config";
import billingRecordsRouter from "./billing-records";
import billingRouter from "./billing";
import buyingHousesRouter from "./buying-houses";
import transactionsRouter from "./transactions";
import analyticsRouter from "./analytics";
import uploadRouter from "./upload";
import fileUploadRouter from "./file-upload";
import rolesRouter from "./roles";
import usersRouter from "./users";
import aiRouter from "./ai";
import billsRouter from "./bills";
import paymentsRouter from "./payments";
import costResourcesRouter from "./cost-resources";
import costModelsRouter from "./cost-models";
import paymentTermsRouter from "./payment-terms";
import clientEventsRouter from "./client-events";

const router: IRouter = Router();

router.use(healthRouter);
router.use(costModelsRouter);
router.use(paymentTermsRouter);
router.use(clientsRouter);
router.use(clientEventsRouter);
router.use(platformsRouter);
router.use(partnerConfigRouter);
router.use(billingRecordsRouter);
router.use(billingRouter);
router.use(buyingHousesRouter);
router.use(transactionsRouter);
router.use(analyticsRouter);
router.use(uploadRouter);
router.use(fileUploadRouter);
router.use(rolesRouter);
router.use(usersRouter);
router.use(aiRouter);
router.use(billsRouter);
router.use(paymentsRouter);
router.use(costResourcesRouter);

export default router;
