export * from "./generated/api";
// TypeScript interface types — export selectively to avoid naming collisions with Zod schemas
export type {
  Alert,
  AlertSeverity,
  AlertType,
  BillingRecord,
  BillingRecordInput,
  Campaign,
  CampaignInput,
  CampaignUpdate,
  Client,
  ClientAnalytics,
  ClientInput,
  ClientUpdate,
  DashboardSummary,
  HealthStatus,
  Partner,
  PartnerAnalytics,
  PartnerInput,
  PartnerUpdate,
  ProfitTimePoint,
  Transaction,
  TransactionInput,
  UploadResult,
} from "./generated/types";
